Repository AY2223S1-CS2103T-T10-1/tp, pull requests merged in 2022-11, with the labels that each got.

#173 Fix error in diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: DG Bug

#182 Fix truncation of long names issue #181
  src/main/resources/view/PersonListCard.fxml
Labels: Functionality Bug

#185 Change `::` to `#`
  docs/DeveloperGuide.md
Labels: DG Bug

#176 Update link documentation in User Guide and address link feature bugs
  docs/UserGuide.md
  docs/images/add-link-after.PNG
  docs/images/add-link-before.PNG
  docs/images/delete-link-after.PNG
  docs/images/delete-link-before.PNG
  src/main/java/seedu/address/logic/commands/OpenLinkCommand.java
  src/main/java/seedu/address/model/module/link/Link.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/OpenLinkCommandTest.java
  src/test/java/seedu/address/model/module/link/LinkTest.java
Labels: UG Bug, Functionality Bug

#179 Update UG (`Task`)
  docs/UserGuide.md
  docs/images/add-task-after.png
  docs/images/add-task-before.png
  docs/images/delete-task-after.png
  docs/images/delete-task-before.png
  docs/images/home-labelled.png
  docs/images/home-page-with-cs2103-circled.png
  docs/images/swap-task-after.png
  docs/images/swap-task-before.png
Labels: UG Bug

#193 Fix headings for `Task`
  docs/UserGuide.md
Labels: UG Bug

#190 Include section for `module-person` association
  docs/DeveloperGuide.md
  docs/diagrams/AddPersonToModuleStep1ObjectDiagram.puml
  docs/diagrams/AddPersonToModuleStep2ObjectDiagram.puml
  docs/diagrams/AddPersonToModuleStep3ObjectDiagram.puml
  docs/images/AddPersonToModuleStep1ObjectDiagram.png
  docs/images/AddPersonToModuleStep2ObjectDiagram.png
  docs/images/AddPersonToModuleStep3ObjectDiagram.png
Labels: DG Bug

#195 Fix formatting in UG (`swap-task`)
  docs/UserGuide.md
Labels: UG Bug

#205 Add description on tasks in UG
  README.md
  docs/UserGuide.md
Labels: UG Bug

#192 Add screenshots to user guide (contacts)
  README.md
  docs/UserGuide.md
  docs/images/add-person-after.png
  docs/images/add-person-before.png
  docs/images/delete-person-after.png
  docs/images/delete-person-before.png
  docs/images/delete-person-from-module-after.png
  docs/images/delete-person-from-module-before.png
  docs/images/edit-person-after.png
  docs/images/edit-person-before.png
Labels: UG Bug
