Repository AY2223S1-CS2103T-T10-1/tp, pull requests merged in 2022-09, with the labels that each got.

#32 Update README.md
  README.md
Labels: type.Task

#35 Fix misplacement of images bug
  docs/AboutUs.md
  docs/images/bluesky0911.png
  docs/images/ekweirui.png
  docs/images/neoshiwen.png
  docs/images/tan-jia-rong.png
  docs/images/teoyuqi.png
Labels: type.Bug

#36 Update user guide
  docs/UserGuide.md
Labels: priority.High

#40 Update AboutUs.md
  docs/AboutUs.md
  docs/images/shwene.png
  docs/team/shwene.md
Labels: type.Bug

#50 Update user guide (navigation)
  docs/UserGuide.md
Labels: type.Task
