Repository AY2223S1-CS2103T-T10-1/tp, pull requests merged in 2022-10, with the labels that each got.

#59 Add model framework for Link, Task and Module
  src/main/java/seedu/address/model/link/Link.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
  src/main/java/seedu/address/model/module/exceptions/ModuleNotFoundException.java
  src/main/java/seedu/address/model/task/Task.java
Labels: type.Task

#60 Add and delete module
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleTitle.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalModulesAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High

#64 Add basic navigation functionalities
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/GoToCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GoToCommandParser.java
  src/main/java/seedu/address/model/module/ModuleCodeMatchesKeywordPredicate.java
  src/main/java/seedu/address/model/person/NameMatchesKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/GoToCommandTest.java
  src/test/java/seedu/address/logic/commands/HomeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GoToCommandParserTest.java
  src/test/java/seedu/address/model/module/ModuleCodeMatchesKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#65 Implement add-link and delete-link command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddLinkCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java
  src/main/java/seedu/address/logic/parser/AddLinkCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteLinkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/link/Link.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/storage/JsonAdaptedLink.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/test/java/seedu/address/logic/commands/AddLinkCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteLinkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddLinkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteLinkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/module/LinkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High

#69 Fix bugs in user guide
  docs/UserGuide.md
Labels: type.Bug

#77 Create a `getModuleFromModuleCode` method to retrieve modules
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/data/JsonSerializableAddressBookTest/typicalModulesAddressBook.json
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Bug

#81 Improve on navigation functionalities
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddLinkCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindModuleCommand.java
  src/main/java/seedu/address/logic/commands/GoToCommand.java
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/ListModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindModuleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/ModuleCodeStartsWithKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/GoToCommandTest.java
  src/test/java/seedu/address/logic/commands/HomeCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/FindModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GoToCommandParserTest.java
  src/test/java/seedu/address/model/module/ModuleCodeMatchesKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/ModuleCodeStartsWithKeywordPredicateTest.java
  src/test/java/seedu/address/model/module/ModuleCodeTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: priority.High

#90 Add `swap-task` command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddLinkCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/SwapTaskNumbersCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SwapTaskNumbersCommandParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/task/TaskList.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/test/data/JsonSerializableAddressBookTest/duplicateIgnoreCaseModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidModuleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalModulesAddressBook.json
  src/test/java/seedu/address/logic/commands/AddLinkCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteLinkCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/SwapTaskNumbersCommandTest.java
  src/test/java/seedu/address/logic/commands/SwapTaskNumbersDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteLinkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SwapTaskNumbersCommandParserTest.java
  src/test/java/seedu/address/model/module/LinkTest.java
  src/test/java/seedu/address/model/module/task/TaskListTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/AddTaskToModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/DeleteTaskFromModuleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/SwapTaskNumbersDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Story

#92 Implement delete contact command by name prefix
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#98 Fix bug: editing person does not edit persons in modules
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
Labels: type.Bug, priority.High, severity.High

#106 Implement sort by module code and name in filtered list
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/model/module/ModuleCodeTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium

#100 Implement `DeletePersonFromModuleCommand`
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePersonFromModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePersonFromModuleCommandParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePersonFromModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonFromModuleCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High

#116 Fix bug in updating module card
  src/main/java/seedu/address/logic/commands/HomeCommand.java
Labels: type.Bug

#152 Fix swap task indexing bug
  src/main/java/seedu/address/logic/commands/SwapTaskNumbersCommand.java
  src/test/java/seedu/address/logic/commands/SwapTaskNumbersCommandTest.java
Labels: type.Bug

#161 Update user guide (Navigation)
  docs/UserGuide.md
Labels: UG Bug
